jobs:
  build:
    docker:
      - image: node:16.17.0
  environment:
      COVERALLS_REPO_TOKEN: P3oVZrkN3ro0EWL1sSTkE4OjWrsvruxHq
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --coverage

- run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info
          version: 2.4
