jobs:
  build:
    docker:
      - image: node:16.17.0
    working_directory: ~/
    steps:
      - checkout:
          path: ~/learn-express
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --coverage